import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css"; // ✅ correct file
import { Providers } from "../context/Providers";

const robotoFont = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"], // جتنے وزن چاہیے وہ add کریں
  variable: "--font-roboto", // Tailwind میں استعمال کرنے کے لیے
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${robotoFont.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
